<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * MeetingRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends EntityRepository
{
	/**
	 * Get teammates
	 *
	 * @param User $user
	 * @return mixed
	 */
	public function getTeamMates( User $user )
	{
		return $this->getEntityManager()
					->getRepository( 'AppBundle:Team' )->getTeamMates( $user );
	}

	/**
	 * Get last Meetings
	 *
	 * @param int $num
	 * @return array
	 */
	public function getLastMeetings( $num )
	{
		return $this->getEntityManager()
					->createQueryBuilder()
					->orderBy( 'date', 'DESC' )
					->setMaxResults( (int)$num )
					->getQuery()
					->getResult();
	}

	public function getAll( $page = 1, $pageSize = 10 )
	{
		if( $page < 1 )
			$page = 1;

		return $this->createQueryBuilder( 'q' )
					->setFirstResult( $pageSize * ( $page - 1 ) )
					->setMaxResults( $pageSize )
					->getQuery()
					->getResult();
	}
}
