<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
	/**
	 * Get teammates
	 *
	 * @param User $user
	 * @return mixed
	 */
	public function getTeamMates( User $user )
	{
		return $user->getTeam()->getUsers();
	}
}
