index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

dashboard_teammates:
    path:     /dashboard/teammates
    defaults: { _controller: AppBundle:Index:getTeammates }

dashboard_last_retrospectives:
    path:     /dashboard/last-retrospectives
    defaults: { _controller: AppBundle:Index:getLastRetrospectives }

dashboard_last_notifications:
    path:     /dashboard/last-notifications
    defaults: { _controller: AppBundle:Index:getLastNotifications }

dashboard_actions:
    path:     /dashboard/actions
    defaults: { _controller: AppBundle:Index:getActions }

create:
    path:     /meeting/create
    defaults: { _controller: AppBundle:Meetings:create }

meeting:
    path:     /meeting/{id}
    defaults: { _controller: AppBundle:Meetings:meeting }
    methods:  [GET]

notes:
    path:     /notes
    defaults: { _controller: AppBundle:Notes:index }

notes_save:
    path:     /notes/save
    defaults: { _controller: AppBundle:Notes:save }
    methods: [POST]

notes_delete:
    path:     /notes/delete
    defaults: { _controller: AppBundle:Notes:delete }
    methods: [POST]

notes_reorder:
    path:     /notes/reorder
    defaults: { _controller: AppBundle:Notes:reorder }
    methods: [POST]

add_job:
    path:     /meeting/{id}/job/{type}
    defaults: { _controller: AppBundle:Meetings:addJob }
    methods: [POST]

get_data:
    path:     /meeting/{id}/data
    defaults: { _controller: AppBundle:Meetings:getData }

add_vote:
    path:     /meeting/{id}/vote
    defaults: { _controller: AppBundle:Meetings:addVote }


add_action:
    path:     /meeting/{id}/vote
    defaults: { _controller: AppBundle:Meetings:addAction }




