index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

create:
    path:     /meeting/create
    defaults: { _controller: AppBundle:Meetings:create }


meeting:
    path:     /meeting/{id}
    defaults: { _controller: AppBundle:Meetings:meeting }
    methods:  [GET]

notes:
    path:     /notes
    defaults: { _controller: AppBundle:Notes:index }

add_job:
    path:     /meeting/{id}/job/{type}
    defaults: { _controller: AppBundle:Meetings:addJob }
    methods: [POST]

get_jobs:
    path:     /meeting/{id}/job
    defaults: { _controller: AppBundle:Meetings:getJobs }




