services:
    note.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Note

    note.service:
        class: AppBundle\Service\NoteService
        arguments: ["@note.repository", "@doctrine.orm.default_entity_manager"]